# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: mariadb_fil_rouge
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3309:3306
  adminer:
    container_name: admin_fil_rouge
    image: adminer
    restart: always
    ports:
      - 9080:8080


